backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "global-config"
    label: "Global Config"
    files:
      - name: "site-config"
        label: "Site Config"
        file: "content/site-config.yml"
        fields:
        - label: "Home Page"
          name: "home-page"
          widget: "relation"
          collection: "pages"
          displayFields: ["name", "title"]
          searchFields: ["title"]
          valueField: "name"

  - name: "pages"
    label: "Pages"
    identifier_field: "name"
    create: true
    folder: "content"
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown"}
      - label: 'Cats'
        name: "cats"
        widget: list
        fields:
          - { label: "Name", name: "name", widget: "string"}
          - { label: "Description", name: "description", widget: "text"}